name: CI

on:
    pull_request:
    push:
        branches: [ master ]

jobs:
    run:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.2'
                    - '7.3'
                    - '7.4'
                minimum_versions: [false]
                include:
                    - description: 'Minimum version'
                      php: '7.2'
                      minimum_versions: true

        name: PHP ${{ matrix.php }} ${{ matrix.description }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: ${{ matrix.php }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install dependencies
              run: composer install
              if: matrix.minimum_versions == false

            - name: Install dependencies lower
              run: composer update --no-interaction --prefer-lowest
              if: matrix.minimum_versions == true

            - name: Run PHPUnit tests
              run: composer run test
